src/django_ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page, contact_page, login_page, register_page
from products.views import ProductListView, ProductDetailView, ProductFeaturedListView, ProductFeaturedDetailView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^contact$', contact_page, name='contact'),
    url(r'^login$', login_page, name='login'),
    url(r'^register$', register_page, name='register'),
    url(r'^products/', include('products.urls', namespace='products'),),
    # url(r'^products$', ProductListView.as_view()),
    # url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    url(r'^admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url, include
from products.views import ProductDetailSlugView, ProductListView, ProductDetailView, ProductFeaturedListView, ProductFeaturedDetailView

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/$', ProductDetailView.ass_view()),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
]

src/products/models.py
from django.db import models
from django.urls import reverse
import os
import random
from django.db.models.signals import pre_save
from .utils import unique_slug_generator

def get_filename_ext(filepath):
    basename = os.path.basename(filepath)
    filename, ext = os.path.splitext(basename)
    return filename, ext

def handle_file_upload(instance, filepath):
    new_filename = random.randint(0, 33647433)
    name, ext = get_filename_ext(filepath)
    final_filepath = "{new_filename}/{new_filename}{ext}".format(new_filename=new_filename, ext=ext)
    return final_filepath

class ProductQuerySet(models.query.QuerySet):
    def featured(self):
        return self.filter(featured=True)

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)
    
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count()==1:
            return qs.first()
        return None

class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    image = models.ImageField(upload_to=handle_file_upload, null=True, blank=True)
    featured = models.BooleanField(default=True)
    slug = models.SlugField(unique=True, blank=True)

    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})

def product_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_reciever, sender=Product)

src/django_ecommerce/forms.py
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()

class ContactForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    email = forms.EmailField()
    content = forms.Textarea()

    def clean_email(self):
        print("asdasd")
        email = self.cleaned_data.get('email')
        if "gmail" not in email:
            raise forms.ValidationError("Has to be a gmail account")
        return email 

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

class RegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("Username already taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email already taken")
        return email

    def clean(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password!=password2:
            raise forms.ValidationError("Passwords dont match")
        return self.cleaned_data

src/django_ecommerce/views.py
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, get_user_model
from .forms import ContactForm, LoginForm, RegisterForm
from django.shortcuts import render, redirect
User = get_user_model()

def home_page(request):
    return render(request, 'home.html')

def contact_page(request):
    print('request.method ', request.method)
    form = ContactForm(request.POST or None)
    context = {
        'form': form
    }
    if form.is_valid():
        print('form.clean', form.cleaned_data)
        context['form'] = ContactForm()
    return render(request, 'contact/view.html', context=context)

def login_page(request):
    context = {}
    form = LoginForm(request.POST or None)
    context['form'] = form
    if form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        print('is_authenticated',request.user.is_authenticated())
        if not request.user.is_authenticated():
            user = authenticate(request=request, username=username, password=password)
            if user:
                login(request, user)
                # context['form'] = LoginForm()
                print('is_authenticated',request.user.is_authenticated())
                return redirect('/')
            else:
                print("Authentication Error")
                return render(request, 'auth/login.html', context=context)
    return render(request, 'auth/login.html', context=context)

def register_page(request):
    context = {}
    form = RegisterForm(request.POST or None)
    context['form'] = form
    if form.is_valid():
        username = form.cleaned_data.get('username') 
        email = form.cleaned_data.get('email') 
        password = form.cleaned_data.get('password') 
        user = User.objects.create(username=username, email=email, password=password)
    return render(request, 'auth/register.html', context=context)

src/products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product

class ProductListView(ListView):
    queryset = Product.objects.all()

class ProductDetailView(DetailView):
    queryset = Product.objects.all()
    
class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()

    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        return Product.objects.filter(slug=slug).first()

class ProductFeaturedListView(ListView):
    queryset = Product.objects.all().featured()

class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()

src/products/templates/products/product_detail.html
<ul>
  <li>
    {{object.title}}
  </li>
  <li>
    {{object.description}}
  </li>
  <li>
    {% if object.image %}
      {{object.image.url}}
    {% endif %}
  </li>
</ul>

src/products/templates/products/product_list.html
{% extends "base.html" %}

{% block content %}
  {% for product in object_list %}
    <div class="col">
      {% include "products/snippets/card.html" with instance=product %}
    </div>
  {% endfor %}
{% endblock content %}

src/products/templates/products/snippets/card.html
<div class="card" style="width: 18rem;">
  {% if instance.image %}
    <img class="card-img-top" src="{{instance.image.url}}" alt="Card image cap">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{instance.title}}</h5>
    <p class="card-text">{{instance.description}}</p>
    <a href="{{instance.get_absolute_url}}" class="btn btn-primary">View</a>
  </div>
</div>

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include "base/css.html" %}
    
    <title>Hello, world!</title>
  </head>
  <body>
    {% include "base/navbar.html" with brand_name="eCommerce" %}
    <div class="container">
      <div class="row">
        {% block content %}{% endblock content %}
      </div>
    </div>
    {% include "base/js.html" %}
  </body>
</html>

src/templates/base/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

src/templates/base/js.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="/static/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as products_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">{{brand_name}}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == products_url %} active {% endif %}">
        <a class="nav-link" href="{{products_url}}">Products</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
        <a class="nav-link" href="{{contact_url}}">Contact</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == 'logout' %} active {% endif %}">
          <a class="nav-link disabled" href="#">Logout</a>
        </li>
      
      {% else %}
        <li class="nav-item {% if request.path == register_url %} active {% endif %}">
          <a class="nav-link disabled" href="{{register_url}}">Register</a>
        </li>
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
          <a class="nav-link disabled" href="{{login_url}}">Login</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

src/templates/contact/view.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1 class="text-center">Hello, world!</h1>
    <div class="container">
      <div class="row">
        <div class="col-12">
          This some sample content.
        </div>
        <div class="col-12">
          <form method="POST">
            {% csrf_token %}
            {% comment %} <input type="text" name="first_name" id=""> {% endcomment %}
            {{form}}
            <input type="submit" value="ok">
          </form>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block content %}
  <h1 class="text-center">Hello, world!</h1>
  <div class="container">
    <div class="row">
      <div class="col">
        This some sample content.
      </div>
    </div>
  </div>
{% endblock content %}